### ISSUE TITLE
How about make this in es6???

### ISSUE THREAD

**Issue by knightpop** [fengdh/mdict-js#2]
I want to use your library with my project..

But your project is made by requirejs and mine is es6....

It's up to you but, how about make this project to es6??

**Comment by fengdh** [comment]
Wish I have time, or someone else to improve it. But sorry right now.

**Comment by knightpop** [comment]
@fengdh Ok, I`ll do when i have time... But I don`t know anything about requirejs, Can I ask you if I have some question?

**Comment by fengdh** [comment]
Yes, of course. You're welcome.

2016年11月8日(火) 12:22 knightpop notifications@github.com:
